/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package scr.view;

import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import scr.dao.connect_to_db;

/**
 *
 * @author admin
 */
public class CapnhatKhoanThuJFrame extends javax.swing.JFrame {

    /**
     * Creates new form CapnhatKhoanThuJFrame
     * @throws java.sql.SQLException
     */
    public CapnhatKhoanThuJFrame() throws SQLException {
        initComponents();       
        java.sql.Connection cons = connect_to_db.getConnection();
        String sql= "UPDATE hokhau_khoanphi SET sotien = ? WHERE mahokhau = ? AND makhoanphi = ?;";
        PreparedStatement ps = cons.prepareStatement(sql);       
       
        btnok.addMouseListener(new MouseAdapter(){
            @Override
            public void mouseClicked(MouseEvent e){
                double pdvcc = Double.parseDouble(jtfpdvcc.getText());
                double pqlcc = Double.parseDouble(jtfpqlcc.getText());
                double pgxm = Double.parseDouble(jtfpgxm.getText());
                double pgot = Double.parseDouble(jtfpgot.getText());
                int mahokhau = Integer.parseInt(jtfmahokhau.getText());        
                
                try {
                    ps.setDouble(1, pdvcc);
                    ps.setInt(2, mahokhau);
                    ps.setInt(3, 1);
                    ps.execute();

                    ps.setDouble(1, pqlcc);
                    ps.setInt(2, mahokhau);
                    ps.setInt(3, 2); 
                    ps.execute();
                   
                    ps.setDouble(1, pgxm);
                    ps.setInt(2, mahokhau);
                    ps.setInt(3, 4); 
                    ps.execute();
                    
                    ps.setDouble(1, pgot);
                    ps.setInt(2, mahokhau);
                    ps.setInt(3, 5);            
                    boolean b = ps.execute();
                    
                    if (!b){
                        jtfMsg.setText("Thành công");
                        jtfMsg.repaint();
                        jtfMsg.revalidate();
                        
                        String sql1= "SELECT sum(sotien) AS sum  FROM hokhau_khoanphi where mahokhau = ?;";
                        PreparedStatement ps1 = cons.prepareStatement(sql1);
                        ps1.setInt(1,mahokhau);
                        ResultSet rs1= ps1.executeQuery();
                        double sum ;
                        if (rs1.next()) {
                            sum = rs1.getDouble("sum");
                        } else {
                            sum = 0; // Nếu không có bản ghi nào
                            }
                        
                        String sql2="UPDATE thongke SET tongsotien = ? WHERE mahokhau = ?;";
                        PreparedStatement ps2 = cons.prepareStatement(sql2);
                        ps2.setDouble(1,sum);
                        ps2.setInt(2,mahokhau);
                        ps2.executeUpdate();  
                    }
                    
                } catch (SQLException ex) {
                    Logger.getLogger(ThongKeJFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jtfpdvcc = new javax.swing.JTextField();
        jtfmahokhau = new javax.swing.JTextField();
        jtfpqlcc = new javax.swing.JTextField();
        jtfpgot = new javax.swing.JTextField();
        jtfpgxm = new javax.swing.JTextField();
        btnok = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jtfMsg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel1.setText("Mã Hộ Khẩu");

        jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel2.setText("Phí dịch vụ chung cư");

        jLabel3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel3.setText("Phí quản lý chung cư");

        jLabel5.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel5.setText("Phí gửi xe máy");

        jLabel6.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel6.setText("Phí gửi ô tô");

        jtfpdvcc.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jtfmahokhau.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jtfmahokhau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfmahokhauActionPerformed(evt);
            }
        });

        jtfpqlcc.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jtfpgot.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jtfpgot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfpgotActionPerformed(evt);
            }
        });

        jtfpgxm.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jtfpgxm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfpgxmActionPerformed(evt);
            }
        });

        btnok.setText("ok");
        btnok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnokActionPerformed(evt);
            }
        });

        jtfMsg.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnok, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(65, 65, 65)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtfpdvcc, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfmahokhau, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfpqlcc, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfpgxm, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfpgot, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jtfMsg, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(208, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnok)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtfMsg, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfmahokhau, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfpdvcc, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfpqlcc, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfpgxm, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfpgot, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtfmahokhauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfmahokhauActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfmahokhauActionPerformed

    private void jtfpgotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfpgotActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfpgotActionPerformed

    private void jtfpgxmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfpgxmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfpgxmActionPerformed

    private void btnokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnokActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnokActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnok;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jtfMsg;
    private javax.swing.JTextField jtfmahokhau;
    private javax.swing.JTextField jtfpdvcc;
    private javax.swing.JTextField jtfpgot;
    private javax.swing.JTextField jtfpgxm;
    private javax.swing.JTextField jtfpqlcc;
    // End of variables declaration//GEN-END:variables
}
